### ISSUE TITLE
🐛  delta 0.4.5 binary release does not run on macOS 10.11 (El Capitan)

### ISSUE THREAD

**Issue by phil-blain** [dandavison/delta#462]
To replicate: 
1. download https://github.com/dandavison/delta/releases/tag/0.4.5 asset delta-0.4.5-x86_64-apple-darwin.tar.gz
2. untar and `cd` to the extracted folder
3. run `./delta --version`:
~~~bash
$ ./delta --version
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/Philippe/Downloads/delta-0.4.5-x86_64-apple-darwin 2/./delta
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/Philippe/Downloads/delta-0.4.5-x86_64-apple-darwin 2/./delta
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
~~~

**Comment by dandavison** [comment]
Thanks @phil-blain. That binary is working for me on MacOS 10.15.7 (Catalina). Quick googling brings up https://github.com/esy/esy/issues/1169#issuecomment-691799356  and https://github.com/nodegui/nodegui/issues/391#issuecomment-582328912 which suggest that the problem is that our GitHub Actions CD is building the MacOS binary on a recent version of MacOS:

```yaml
        job:
          - { os: macos-latest,   target: x86_64-apple-darwin,         use-cross: false }
```
 
So one possibility would be to re-release with that `os:` set to an older version. However https://github.com/dandavison/delta/issues/463 reports that a binary is not working on Ubuntu 20.04, which I am still investigating. cc @MarcoIeni

**Comment by MarcoIeni** [comment]
> So one possibility would be to re-release with that `os:` set to an older version.

Sadly GitHub actions only support:
- macOS Catalina 10.15 (`macos-latest` or `macos-10.15`) (this is what we are using)
- macOS Big Sur 11.0 (`macos-11.0`)

See https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

I believe there is no older version.

**Comment by dandavison** [comment]
Hm, that's a shame. What should we do? MacOS users do have Homebrew and MacPorts as installation options. We could revert to Travis if we had to.

**Comment by MarcoIeni** [comment]
Travis uses mac os 10.13, see https://docs.travis-ci.com/user/reference/osx/#macos-version
But I think it's just a matter of time that they do the upgrade, too, so reverting to Travis might be useless in a couple of months, I don't know.

If it was my project I would remove support for El Captain for released binaries. Sorry to say this, but given what we know at the moment it might be the better choice in terms of threadoff between maintainers effort and users happiness :(
El Captain users could always [build](https://github.com/dandavison/delta#build-delta-from-source) from scratch or use the other methods you have mentioned, which I am not familiar with.

Anyway it's up to you Dan!

**Comment by dandavison** [comment]
> If it was my project I would remove support for El Captain for released binaries.

Yes, I think agree.  I've added a note to the README (If anyone knows where the problem starts in the El Capitan - Sierra - High Sierra - Mojave - Catalina sequence let me know and I can improve the README.)

Does this seem like the right decision to you @phil-blain? Are you OK installing from brew or cargo or source?

**Comment by phil-blain** [comment]
Well it's not the answer I was hoping for (10.11.6 is just over 2 years old, it's not that much), but as Marcoleni says it's your project :)

As far as I know, it's possible to build on newer macOS releases but target older releases, for example with `clang` you would use `-mmacosx-version-min=10.11` or the environment variable `MACOSX_DEPLOYMENT_TARGET`. The rust book seems to imply that using this variable works, see https://rust-cli.github.io/book/tutorial/packaging.html#building-binary-releases-on-ci and the example linked there: https://github.com/rustwasm/wasm-pack/blob/51e6351c28fbd40745719e6d4a7bf26dadd30c85/.travis.yml#L85-L91


For now I've installed rust, and then delta using cargo. (Homebrew is really a pain to use on older systems because of its rolling release policy;  it always wants to recompile OpenSSL  *each time* I want to install a new package...)

**Comment by MarcoIeni** [comment]
Do you want to try to solve this?
You can:
- fork the repository
- edit the [cd](https://github.com/dandavison/delta/blob/master/.github/workflows/cd.yml) in order to add the environment variable on mac os
- create a tag in order to trigger the github action
- download the binary and try it on your machine
- submit a PR if that works

If have questions I can help you!

**Comment by phil-blain** [comment]
I tried that and it works: see  https://github.com/phil-blain/delta/releases/tag/0.4.6 and https://github.com/phil-blain/delta/commit/9c71fbaf42020d75d283dc716022ec5d8fcde300

I added the variable to the environment for all jobs; the change was simpler this way and it should not cause any problem on non-macOS platforms. I'll submit a PR .

**Comment by dandavison** [comment]
Thanks @phil-blain, that sounds great.
